# Generated by Django 6.0 on 2026-01-21 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_movie', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='movie/')),
                ('description', models.TextField()),
                ('jenre_movies', models.CharField(choices=[('Боевик', 'Боевик'), ('Драмма', 'Драмма'), ('Фантастика', 'Фантастика'), ('Ужасы', 'Ужасы'), ('Триллер', 'Триллер'), ('Документальное', 'Документальное')], default='Боевик', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(choices=[('🌟', '🌟'), ('🌟🌟', '🌟🌟'), ('🌟🌟🌟', '🌟🌟🌟'), ('🌟🌟🌟🌟', '🌟🌟🌟🌟'), ('🌟🌟🌟🌟🌟', '🌟🌟🌟🌟🌟')], default='🌟', max_length=100)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='CineBoard.movies')),
            ],
        ),
    ]
