# Generated by Django 6.0 on 2026-01-18 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
        ('products', '0003_alter_products_type_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='basket',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='products.products'),
        ),
    ]
