# Generated by Django 6.0 on 2026-01-18 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_remove_basket_updated_at_basket_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'tasks', 'verbose_name_plural': 'task'},
        ),
    ]
