# Generated by Django 6.0 on 2026-01-18 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_alter_basket_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='name',
            new_name='name_basket',
        ),
    ]
