# Generated by Django 6.0 on 2026-01-18 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_rename_name_basket_name_basket'),
        ('products', '0003_alter_products_type_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='products.products'),
        ),
    ]
