# Generated by Django 6.0 on 2026-01-18 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_alter_basket_product'),
        ('products', '0003_alter_products_type_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='basket_images/'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Enter your phone number'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='products.products'),
        ),
    ]
