# Generated by Django 6.0 on 2026-01-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_basket_image_alter_basket_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='image',
        ),
    ]
