# Generated by Django 6.0 on 2026-01-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_products', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='blog/')),
                ('description', models.TextField()),
                ('type_products', models.CharField(choices=[('Sweet', 'Sweet'), ('Spicy', 'Spicy'), ('Salty', 'Salty'), ('Sour', 'Sour'), ('Oily', 'Oily')], default='Sweet', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
