# Generated by Django 6.0 on 2026-01-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='type_products',
            field=models.CharField(choices=[('Sweet', 'Sweet'), ('Spicy', 'Spicy'), ('Salty', 'Salty'), ('Sour', 'Sour'), ('Oily', 'Oily'), ('Masterpiece', 'Masterpiece')], default='Sweet', max_length=100),
        ),
    ]
